#version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile.app
    container_name: resilient-api
    ports:
      - "5002:5002"
    restart: always

  locust:
    build:
      context: .
      dockerfile: dockerfile.locust.l
    container_name: locust-tester
    ports:
      - "8090:8089" #remaping 8090 t0 8089
    depends_on:
      - app

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards

    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin